### ISSUE TITLE
Error after upgrading to 0.4.2

### ISSUE THREAD

**Issue by fazibear** [opal/opal-sprockets#14]
After upgrading a see and error:

```
Using opal-sprockets 0.4.2.0.11.0.3.1 (was 0.4.1.0.11.0.3.1)
```

```
NameError: uninitialized constant Opal::Sprockets::SourceMapHeaderPatch
  /usr/local/lib/ruby/gems/2.5.0/gems/inesita-0.8.1/lib/inesita/server.rb:94:in `create_source_maps_app'
  /usr/local/lib/ruby/gems/2.5.0/gems/inesita-0.8.1/lib/inesita/server.rb:18:in `initialize'
  config.ru:9:in `new'
  config.ru:9:in `block in <main>'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:283:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:148:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/inesita-0.8.1/lib/inesita/cli/server.rb:21:in `server'
  /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/inesita-0.8.1/bin/inesita:5:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.5.0/bin/inesita:23:in `load'
  /usr/local/lib/ruby/gems/2.5.0/bin/inesita:23:in `<top (required)>'
```

For sure it's an inesita issue, but I'm trying to figure out what has changed. 

Here is an example of server code from inesita:

```ruby
    def create_app
      assets_app = @assets_app
      source_maps_app = @source_maps_app
      static_dir = @static_dir

      Rack::Builder.new do
        use Rack::Static, :urls => [static_dir]

        use Rack::Rewrite do
          rewrite(/^(?!#{Config::ASSETS_PREFIX}|#{Config::SOURCE_MAP_PREFIX}).*/, Config::ASSETS_PREFIX)
        end

        map Config::ASSETS_PREFIX do
          run assets_app
        end

        map Config::SOURCE_MAP_PREFIX do
          run source_maps_app
        end
      end
    end

    def create_source_maps_app
      ::Opal::Sprockets::SourceMapHeaderPatch.inject!(Config::SOURCE_MAP_PREFIX)
      Opal::SourceMapServer.new(@assets_app, Config::SOURCE_MAP_PREFIX)
    end

```

Should I just remove `source_maps_app` and maps will be served by assets_app?

**Comment by fazibear** [comment]
Nevermind, remove all source_maps app, and it working fine.

**Comment by elia** [comment]
@fazibear I'm wondering if I should keep that stuff around and make it just a noop 🤔 but probably there are not many other libraries using it directly…

**Comment by fazibear** [comment]
@elia It's not a problem now, because I've fixed `inesita`, and it will work after `bundle update` the problem is that I've no idea that somethings has changed, and new `inesita` project just won't work anymore. It's hard to track or lock version of this gem.
